import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-outside-counsel-legal-invoice-audit",
  "engine": "recovery",
  "title": "Outside Counsel Legal Invoice Audit",
  "shortTitle": "Legal Spend Recovery",
  "tagline": "Enforce billing guidelines and recover unsupported legal spend at line-item precision",
  "industry": "Legal Operations Spend Management",
  "uiPort": 4565,
  "apiPort": 5565,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Outside-counsel invoice leakage prevented or recovered with guideline evidence",
  "valueNarrative": "Reconcile engagement letters, rate cards, timekeeper approvals, LEDES entries, matter budgets, tasks, expenses, and outcomes.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "compliantAmount",
    "actualLabel": "Firm billed amount",
    "expectedLabel": "Guideline-compliant amount",
    "varianceLabel": "Potential legal spend recovery",
    "direction": "actual-minus-expected",
    "finding": "LEDES, rate, staffing, task, expense, and billing-guideline evidence identify unsupported outside-counsel spend.",
    "actions": [
      "Validate invoice syntax, matter, timekeeper, and rates",
      "Apply billing guideline and engagement terms line by line",
      "Route exceptions for legal-owner review",
      "Issue adjustment and reconcile approved invoice"
    ]
  }
},[
feature("firm-and-engagement-library","LSR01","Firm and engagement library","Reconcile firm and engagement library using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed firm and engagement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("matter-and-budget-registry","LSR02","Matter and budget registry","Reconcile matter and budget registry using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed matter and budget registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("ledes-invoice-ingestion","LSR03","LEDES invoice ingestion","Reconcile ledes invoice ingestion using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed ledes invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("timekeeper-authorization","LSR04","Timekeeper authorization","Reconcile timekeeper authorization using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed timekeeper authorization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("rate-and-increase-validation","LSR05","Rate and increase validation","Reconcile rate and increase validation using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed rate and increase validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("block-billing-detection","LSR06","Block billing detection","Reconcile block billing detection using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed block billing detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("duplicate-time-and-expense-detection","LSR07","Duplicate time and expense detection","Reconcile duplicate time and expense detection using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed duplicate time and expense detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("task-and-activity-code-validation","LSR08","Task and activity code validation","Reconcile task and activity code validation using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed task and activity code validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("staffing-and-seniority-review","LSR09","Staffing and seniority review","Reconcile staffing and seniority review using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed staffing and seniority review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("travel-and-disbursement-audit","LSR10","Travel and disbursement audit","Reconcile travel and disbursement audit using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed travel and disbursement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("billing-guideline-rules-engine","LSR11","Billing-guideline rules engine","Reconcile billing-guideline rules engine using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed billing-guideline rules engine decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("invoice-exception-workbench","LSR12","Invoice exception workbench","Reconcile invoice exception workbench using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed invoice exception workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("legal-owner-approval-workflow","LSR13","Legal owner approval workflow","Reconcile legal owner approval workflow using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed legal owner approval workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("adjustment-and-payment-reconciliation","LSR14","Adjustment and payment reconciliation","Reconcile adjustment and payment reconciliation using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed adjustment and payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]}),
feature("firm-matter-and-savings-analytics","LSR15","Firm matter and savings analytics","Reconcile firm matter and savings analytics using engagement letters, billing guidelines, approved rates, timekeepers, LEDES entries, matter budgets, tasks, expenses, and prior decisions.","Produce a governed firm matter and savings analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["lawFirm","Law Firm","text","Barton & Cole LLP"],["invoiceMatter","Invoice / Matter","text","INV-88420 / MAT-184"],["billedAmount","Firm Billed Amount","currency",486000],["compliantAmount","Guideline-Compliant Amount","currency",421500]],{amountField:"billedAmount",subjects:["Litigation matter","Regulatory investigation","M&A transaction","Employment matter","Intellectual property portfolio"]})
]);
